homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:
  
# homematic:
#   hosts:
#     wired:
#       ip: !secret homematic_ip
#       resolvenames: xml

homematic:
  interfaces:
    rf:
      host: !secret homematic_ip
      resolvenames: json
      # username: Admin
      # password: secret
      primary: true
      variables: true
    wired:
      host: !secret homematic_ip
      port: 2000
      resolvenames: json
      # username: Admin
      # password: secret
    ip:
      host: !secret homematic_ip
      port: 2010
    groups:
      host: !secret homematic_ip
      port: 9292
      resolvenames: json
      # username: Admin
      # password: secret
      path: /groups
  hosts:
    ccu2:
      host: !secret homematic_ip
      # username: Admin
      # password: secret

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:
  
# iOS Platform
ios:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
